### ISSUE TITLE
MouseTerm vs MouseTerm Plus

### ISSUE THREAD

**Issue by ardecvz** [saitoha/mouseterm-plus#1]
Hello, @saitoha!

Could you kindly clarify whether there are any plans to merge MouseTerm Plus' changes into the original MouseTerm in the near future?

(I've faced that vim with ```set mouse=a``` and activated original MouseTerm erroneously turn on ```visual mode``` on empty lines; in your version it seems to be fixed)

If it's unacceptable, would it be OK to include your version in homebrew-cask repository and possibly simplify future installs by homebrew? And which compiled version from your server should I use - [MouseTerm-Plus.dmg](http://zuse.jp/misc/MouseTerm-Plus.dmg) or [Mouseterm-Plus.dmg (with lowercase T, a more recent version)](http://zuse.jp/misc/Mouseterm-Plus.dmg)?

And huge thanks for a really useful piece of software!

**Comment by ELLIOTTCABLE** [comment]
@ardecvz any updates on your intentions of submitting MouseTerm-Plus to `homebrew-cask`?

**Comment by ardecvz** [comment]
I'm sorry for my long absence in the thread.

@saitoha As you have already realized, no rush was intended ;) But we certainly should include your work in [cask](https://github.com/caskroom/homebrew-cask) exclusively so users who interested in mouseterm could get a supported version only. By the way, thank you for tagged releases - really conventional!

@ELLIOTTCABLE please feel free to participate in caskroom/homebrew-cask#7519. I'm not sure about the best way to add SIMBL plugins to the formulae (there're a lot of plugins without installer / uninstaller).

I'll send a pull request with the installation instructions as soon as the cask's team make a decision.
