### ISSUE TITLE
El Capitan 10.11 support

### ISSUE THREAD

**Issue by choco** [saitoha/mouseterm-plus#10]
Today I installed the GM of El Capitan and with much surprise, mouse support has been finally added!
I still think mouseterm has its reason to be, since not only it provides mouse support but also a number of other features that enhance the Terminal.app use.
So I just wanted to open an issue and discuss if there are any plans to support the new OS. Obviously I'd be glad to help in any way possible.

**Comment by saitoha** [comment]
@cHoco It's a good news. I'm interested in it but I have not installed it yet.
I'll examine new Terminal.app in a few days and check which type of mouse mode is supported by it.

**Comment by floam** [comment]
Can one disable SIP, install SIMBLE, reenable it, and use this effectively?

**Comment by cHoco** [comment]
@floam Yes, I personally do that. It doesn't seem to work with apps that are started at login (like Finder) but if I remember correctly that was an old SIMBL limitation. Here's the link to the procedure: https://github.com/norio-nomura/EasySIMBL/issues/26#issuecomment-117028426
