### ISSUE TITLE
Issue with option and text selection

### ISSUE THREAD

**Issue by chiedojohn** [saitoha/mouseterm-plus#4]
Hey fellas,
When I hold option and select text for copying and pasting in something like TMUX for example, the selection won't persist. This works fine on the standard mouseterm but is quite buggy on mouseterm-plus.

Any ideas?

**Comment by saitoha** [comment]
> the selection won't persist.

@chiedojohn Reproduced. Thanks for reporting.

**Comment by saitoha** [comment]
I published new pre-release that includes some improvement for this issue. Please try it out.
https://github.com/saitoha/mouseterm-plus/releases/tag/plus-1.0a6-hotfix-issue4

**Comment by chiedojohn** [comment]
Thanks for the quick response and fix! It worked like a charm. :)
