### ISSUE TITLE
DECSCUSR support

### ISSUE THREAD

**Issue by cHoco** [saitoha/mouseterm-plus#5]
I was looking at implementing DECSCUSR in Terminal app using mouseterm-plus. Firstly I wanted to figure out how the app handles different cursors. 
As of my understanding the drawing is done in the ```drawCursorInMarkedText:``` method in the ```TTView``` class. The the type of cursor drawn is determined by the type defined in the ```TTProfile``` dictionary using the value of the keys ```CursorType``` and ```CursorBlink```
So we should just change the value in this dictionary for the active profile and we should be good to go since its values are observed for change.

Now comes the difficult part, parsing the xterm escape sequence. For mouseterm the job seems to be done by the ```MTParser_execute``` function, but I wasn't able to understand how it works so I figured I'd post here and ask for help :)
In the meantime let me congratulate for your awesome work :) I've been using this plugin for a long time since I prefer Terminal.app text rendering to iTerm and your project made this choice easier since it brings some excellent and missed features!

**Comment by saitoha** [comment]
[ECMA-48](http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-048.pdf) defines the generic format of control sequences (see 5.4 Control sequences)

`CSI P ... P I ... I F`

a) `CSI` is 01/11 and 05/11 in a 7-bit code
b) `P ... P` are `Parameter Bytes` (03/00 to 03/15)
c) `I ... I` are `Intermediate Bytes` (02/00 to 02/15)
d) `F` is the `Final Byte` (04/00 to 07/14)

`DECSCUSR` (`CSI Ps SP q`) is one of that variations.

To parse such terminal sequences, mouseterm-plus has almost-full featured VT-parser.

![vt500_parser](https://cloud.githubusercontent.com/assets/1162739/7753376/fa7981a4-001f-11e5-801e-b2eedc7b59dc.png)

The huge switch statement in `MTParser_execute()` represents above state machine.
Each switch labels in it represents above parser states.

To parse `DECSCUSR` (`CSI Ps SP q`), the parser state switches as follows  (as red line).

`PS_GROUND` -> `PS_ESCAPE` -> `PS_CSI_ENTRY` -> `PS_CSI_PARAM` -> `PS_CSI_INTERMEDIATE` -> `PS_GROUND`

During above transitions, the parser memorizes `Parameter Bytes` as `ppc->params`, and accumulates `Intermediate Bytes` and `Final Bytes` to `ppc->action`.

In case of `DECSCUSR`, `ppc->action` always equals `0x2071` (== ' ' << 8 | 'q').
So you can handle it by adding the following case label in csi_dispatch().

```
diff --git a/MTParser.m b/MTParser.m
index 2cb81d5..2578114 100644
--- a/MTParser.m
+++ b/MTParser.m
@@ -828,6 +828,34 @@ static void csi_dispatch(struct parse_context *ppc, char *p, MTShell *shell)
                                                         length: response.length]];
         }
         break;
+    case (' ' << 8) | 'q':  /* DECSCUSR */
+        if (ppc->params_index < 1)
+            ppc->params[0] = 0;  /* default parameter as 0 */
+        switch (ppc->params[0]) {
+        case 0:
+        case 1:
+            /* blink block (default) */
+            break;
+        case 2:
+            /* steady block */
+            break;
+        case 3:
+            /* blink underline */
+            break;
+        case 4:
+            /* steady underline */
+            break;
+        case 5:
+            /* blink bar */
+            break;
+        case 6:
+            /* steady bar */
+            break;
+        default:
+            /* ignore */
+            break;
+        }
+        break;
     case 't':
         if (ppc->params_index > 0) {
             switch (ppc->params[0]) {
```

**Comment by cHoco** [comment]
Thank you so much for the great answer! Now I kinda understand better the code logic, I'll keep studying the links you gave me to have a better idea on how terminals work :)

Anyway thanks to your code I added support for changing the cursor shape, here's the pull request (https://github.com/saitoha/mouseterm-plus/pull/6), you may want to take a look! Again, thank your for the awesome answer.
